config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  namespace :reports do
    resources :searches, only: :index
  end
  
  resources :reports do
    #コメント情報を作る機能
    resources :comments, only: :create

    collection do
      get :search
    end

  end

  namespace :api do
    resources :categorys, only: :index, defaults: { format: 'json' }
  end

  
  root "tops#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :reports

  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :report
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments

  #reportテーブルから検索するというメソッドのため、modelに記述
  def self.search(search)
    #引数で渡されるsearchの中身に何もなければ全ての投稿を取得できる
    return Report.all unless search
    Report.where('title LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reports
  has_many :comments
  validates :name, presence:true
end

app/controllers/api/categorys_controller.rb
class Api::CategorysController < ApplicationController
  def index
    @category = Category.find(params[:keyword]).children

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  

  protected
  
  #入力フォームからアカウント名情報をDBに保存するため
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    #ストロングパラメーターを使って、インスタンス変数に代入
    @comment = Comment.new(comment_params)
    #itemテーブルからitem_idを見つけ、インスタンス変数にいれる
    @report = Report.find(params[:report_id])
    #コメントが保存できたら
    if @comment.save
      #item詳細に飛ぶ
      redirect_to report_path(@report)
    else
      #保存失敗したらフラッシュメッセージ表示
      flash[:notice] = "コメント欄が空白です。"
      redirect_to report_path(@report)
    end
  end

  private
  #reviewカラムには渡されたparamsの中にcommentというハッシュがある二重構造になっているので、requireメソッドで指定してtextを取り出す。
  #user_idカラムには、ログインしているユーザーのidとなるcurrent_user.idを保存し、item_idカラムは、paramsで渡されるようにするので、params[:item_id]として保存する
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, report_id: params[:report_id])
  end
end

app/controllers/reports/searches_controller.rb
class Reports::SearchesController < ApplicationController
  #検索結果の一覧表示するアクション定義
  def index
    @reports = Report.search(params[:keyword])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @report = Report.all.order(updated_at: :desc)
  end
  
  def new
    @report = Report.new
  end

  def show
    @report = Report.find(params[:id])
    @comment = Comment.new
    @comments = @report.comments.includes(:user)
  end

  def create
    Report.create(report_params) 
    redirect_to root_path
  end

  def update
    @report = Report.find(params[:id])
  end

  def search
  end

  private
    def  report_params
      params.require(:report).permit(:title, :review, :url,:category_id).merge(user_id: current_user.id)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @report = Report.all.order(updated_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reports/searches_helper.rb
module Reports::SearchesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/_footer.html.haml
.footer
 .footer__contents
  .footer__contents__content1
   %h3 About Book-Worm
   %ul
    %li  
    = link_to root_path do
     What Is It？
    %li
    = link_to root_path do
     How To Use
    %li
    = link_to root_path do
     Rule
  .footer__contents__content2
   %h3 Recommended Site To Review
   %ul
    %li  
    = link_to "https://www.amazon.co.jp/" do
     Amazon
    %li
    = link_to "https://www.youtube.com/?gl=JP&hl=ja" do
     You Tube
    %li
    = link_to "https://note.com/" do
     note
 .footer__logo
  %h3 Copy right ©︎Grow-Up

app/views/layouts/_header.html.haml
.header
 .header__letter
  %h1 book,movie,web and so on

 .header__log
  -if user_signed_in?
   .header__log__left
   =link_to "Log Out", destroy_user_session_path, method: :delete
   .header__log__right
   =link_to "edit", edit_user_registration_path
      
  - else
   .header__log__left
   =link_to "Sign-Up", new_user_registration_path 
    
   .header__log__right
   =link_to "Log In", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyAppOutput
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/reports/index.html.haml
.search 
 -@report.each do |report|
  .search__box
   = link_to "/reports/#{report.id}", method: :get do
    .search__box__1
     = report.title

app/views/reports/new.html.haml
%h1 投稿
= form_for @report do |f|
  %p
    = f.label :タイトル
    %br/
    = f.text_field :title

  %p
    = f.label :カテゴリー
    %br/
    .exhibition__detail__cat
      = f.collection_select :category_id, Category.roots, :id, :name, {prompt: "------"}, {class: "aaaaa"}

  %p
    = f.label :ウェブサイト
    %br/
    = f.text_field :url
  %p
    = f.label :レビュー
    %br/
    = f.text_area :review
  %p
    = f.submit

app/views/reports/search.html.haml
.main1

  .main1__search-box
    = form_with(url: reports_searches_path, local: true, method: :get, class: "main1__search-box__box") do |f|
      = f.text_field :keyword, placeholder: "Search", class: "main1__search-box__box__text"
      = image_submit_tag 'icons8-ios-50.png',height: '51px',width: '51px',class: "main1__search-box__box__btn"

  .main1__text 
    = link_to "Back", root_path,class:"main1__text__inner"

app/views/reports/searches/index.html.haml
.search 
 -@reports.each do |report|
  .search__box
   = report.title
   

app/views/reports/show.html.haml
%h1 タイトル
= @report.title

%h1 カテゴリー
= @report.category.name

%h1 URL
= @report.url
%h1 レビュー
= @report.review

.message-content
  /form_withでcomment#createに飛ばす
  = form_with(model: [@report,@comment], local: true, class: "message-content__form") do |form|
    = form.text_area :text, type: "text", class: "message-content__form--textarea"
    %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    = form.submit "コメントする" ,type: "submit", class: "message-content__form--submit"
.comment
  <コメント一覧>
  .comment__inner
    /itemに紐づくコメントをコメントテーブルから取り出す
    - @comments.each do |comment|
      .comment__inner__box
        = link_to comment.user.name,root_path,class: "comment__inner__box__name"
        .comment__inner__box__text
          = comment.text

app/views/tops/index.html.haml
.main
 .main__side
  .main__side__content
   %button#hamburgerbtn
    %span
    %span
    %span
   

  .main__side__nav
   #graylayer
    %ul#slidemenu
     %button#hamburgerbtn1
      %span
      %span
      %span
     %h3 menu 

     %li
      =link_to "Post", new_report_path
     %li
      =link_to "Post All", reports_path

     %h4 category

     %li
      =link_to "Book", root_path
     %li
      =link_to "Movie", root_path
     %li
      =link_to "WebSite", root_path
      

  .main__side__search
  = link_to search_reports_path do
   = image_tag 'icons8-ios-50.png',height: '30px',width:'30px',class:'main__side__search__logo'
    
  

  %h2 BOOK-WORM

 .main__right
  .main__right__top
   .main__right__top__box
   = image_tag 'reading-1246520_1280.jpg',height: '500px',width:'800px',class:'main__right__top__picture'

  .main__right__bottom
   -@report.first(1).each do |report|
    .main__right__bottom__title
     = link_to "/reports/#{report.id}", method: :get do
      .main__right__bottom__title__name
       Today Recommend : 
       = report.title
    .main__right__bottom__phrase
     "People don't realize how a man's
     %br
     whole life can be changed by one book"
    .main__right__bottom__name
     by Malcolm X


    
 